
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Button gtkBtn;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.gtkBtn = new global::Gtk.Button();
		global::Gtk.Tooltips w1 = new Gtk.Tooltips();
		w1.SetTip(this.gtkBtn, "Native Button", "Native Button");
		this.gtkBtn.CanFocus = true;
		this.gtkBtn.Name = "gtkBtn";
		this.gtkBtn.UseUnderline = true;
		this.gtkBtn.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.vbox1.Add(this.gtkBtn);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.gtkBtn]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 800;
		this.DefaultHeight = 600;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}